test8

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -68,9 +68,18 @@ jobs:
         if: github.ref == 'refs/heads/main'
         run: sleep 20
 
-      # 1️⃣1️⃣ Test the API
-      - name: Read API URL
-        working-directory: terraform
+      - name: Test Resume API
         run: |
-          echo "API_URL=$(terraform output -raw api_base_url)/resume" >> $GITHUB_ENV
+          echo "Testing $API_URL"
+          RESPONSE=$(curl -s -w "%{http_code}" -o response.json "$API_URL/101")
+          HTTP_CODE=$(tail -n1 <<< "$RESPONSE")
+
+          if [ "$HTTP_CODE" != "200" ]; then
+          echo "API test failed with status $HTTP_CODE"
+          cat response.json
+          exit 1
+          fi
+
+          echo "API test passed!"
+          cat response.json
         
